### ISSUE TITLE
correct way to pick up environment_variables.yml

### ISSUE THREAD

**Issue by jgreidy** [buntine/discogs-oauth#7]
Thanks for this! Perfect for learning discogs.com API and ruby at the same time.

I didn't know the correct way to include my environment_variables.yml file, and it wasn't being discovered, so I added this to application.rb:

ENV.update YAML.load_file('config/environment_variables.yml')[Rails.env] rescue {}

What is the correct way to get this file in play?

**Comment by buntine** [comment]
Ahh, yes, it looks like this was introduced in a pull request. I believe the submitter was going for something like this: https://richonrails.com/articles/environment-variables-in-ruby-on-rails

I think I prefer your approach, but maybe you try somethnig like this to as I'm not sure relative paths will always work and so it works on non-unix systems:
```
ENV.update(YAML.load_file(File.join(Rails.root, "config", "environment_variables.yml"))[Rails.env])
```

**Comment by jgreidy** [comment]
Hi,
Yes I will try that - more ruby magic. Thanks again for the example code.
I got a php discogs example working earlier (finally), but your ruby
example is a lot nicer to work with.
-JGReidy

**Comment by buntine** [comment]
Thanks. :)
