### ISSUE TITLE
Difficulty running

### ISSUE THREAD

**Issue by postalcurve** [buntine/discogs-oauth#8]
Hi, 

Thanks for the contribution. I downloaded the zip file however I'm getting errors when trying to bundle install. Has this version become deprecated now?

Thanks

**Comment by buntine** [comment]
Thanks, I'll give it a shot.

**Comment by buntine** [comment]
I've cloned the repository and bundled successfully with Ruby 2.2.1

Can you please give me some more information about your error? Feel free to paste the error message and stack trace here for me to look over.
